### ISSUE TITLE
Invisible text in Gnome Calendar

### ISSUE THREAD

**Issue by chrisirwin** [snwh/paper-gtk-theme#263] opened 2016-01-27 19:07 UTC
The month text is not visible in Gnome Calendar.

Screenshot:

![calendar-paper](https://cloud.githubusercontent.com/assets/6145931/12624853/15c4882e-c4ff-11e5-8354-038d0ab62311.png)

Compare with Adwaita:

![calendar-adwaita](https://cloud.githubusercontent.com/assets/6145931/12624855/183ddbf0-c4ff-11e5-8320-b9c4003076be.png)

Additionally, a visible grid would be preferable.

**Comment by snwh** [comment] 2016-03-16 21:08
A lot of GNOME calendar's css is baked into Adwaita, I've tried to theme it. :/

**Comment by snwh** [comment] 2016-03-16 21:22
duplicate of #223

**Closed by snwh** 2016-03-16 21:22 UTC
