### ISSUE TITLE
No differences between active and inactive elements in menus / Ubuntu 15.10 / Unity

### ISSUE THREAD

**Issue by Hybrid512** [snwh/paper-gtk-theme#309] opened 2016-04-18 10:32 UTC
Version : 2.0+r202~daily~ubuntu15.10.1

With GTK menus such as in gedit, it is nearly impossible to distinguish active elements from inactive ones.

![capture du 2016-04-18 11-47-35](https://cloud.githubusercontent.com/assets/18528623/14601270/94e940fc-0561-11e6-9948-05d87980739d.png)

**Comment by Narrat** [comment] 2016-04-18 10:57
I suppose this is a duplicate of this https://github.com/snwh/paper-gtk-theme/issues/303

**Comment by snwh** [comment] 2016-04-18 14:35
Correct

**Closed by snwh** 2016-04-18 14:35 UTC
