### ISSUE TITLE
Disks

### ISSUE THREAD

**Issue by watgrad** [snwh/paper-gtk-theme#103] opened 2015-03-12 17:18 UTC
Hi - great theme.
The disks app has an issue.  The selected partition disappears (maybe because the text turns white on a white background?).
In the Adwatia theme, the selected partition is blue, and the partition information is white, so it is readable.

Thanks for a great theme.

**Comment by snwh** [comment] 2015-03-12 17:37
Duplicate of #58

**Closed by snwh** 2015-03-12 17:37 UTC
