### ISSUE TITLE
Gnome Calendar - Archlinux

### ISSUE THREAD

**Issue by roidm** [snwh/paper-gtk-theme#151] opened 2015-04-27 10:26 UTC
Paper and gnome-calendar  
take a look at the screenshots

![screenshot from 2015-04-27 12-16-08](https://cloud.githubusercontent.com/assets/1218563/7345757/4319552a-ecd8-11e4-8627-27b270d92d01.png)
![screenshot from 2015-04-27 12-16-21](https://cloud.githubusercontent.com/assets/1218563/7345759/4880804c-ecd8-11e4-8b12-92104219a9d0.png)

using adwaita 

![screenshot from 2015-04-27 12-25-29](https://cloud.githubusercontent.com/assets/1218563/7345789/8acd8ada-ecd8-11e4-9e83-a4df8e364c9c.png)

![screenshot from 2015-04-27 12-21-04](https://cloud.githubusercontent.com/assets/1218563/7345762/4e8c4214-ecd8-11e4-8632-65eea57bfbfa.png)

**Comment by HeikoAdams** [comment] 2015-04-27 17:56
seems to be fixed with current git snapshot

**Comment by roidm** [comment] 2015-04-28 07:38
sorry but not here

**Comment by snwh** [comment] 2016-03-16 21:21
I'm going to mark this duplicate of #223

**Closed by snwh** 2016-03-16 21:21 UTC
