### ISSUE TITLE
Gnome terminal resize issue

### ISSUE THREAD

**Issue by alseambusher** [snwh/paper-gtk-theme#229] opened 2015-10-10 18:50 UTC
In Ubuntu gtk-3 when i resize my gnome terminal, it keeps shrinking infinitesimally.

![terminal](https://cloud.githubusercontent.com/assets/1242542/10412765/fad6915c-6f44-11e5-9650-80ab39fd75d8.png)

**Comment by Defman21** [comment] 2015-10-10 19:35
Duplicate of #66

**Closed** 2015-10-10 20:02 UTC
