### ISSUE TITLE
Unthemed or bugged file explorer active tabs

### ISSUE THREAD

**Issue by Darlelet** [snwh/paper-gtk-theme#204] opened 2015-07-24 23:01 UTC
Hi, 
So first I would like to compliment you, you did a very great job! :)

So basically I created this issue in order to know if I'm the only one facing this issue, and if there might be a way to fix it.

Here is my problem:

Apparently about the whole theme is working properly on my Ubuntu Desktop 14.04 LTS version, except the explorer that seems to be rather unfunctional (All active tabs seem to be unthemed, just lighten up instead of being darken, refer to this screenshot).

![buggy](https://cloud.githubusercontent.com/assets/6534701/8886243/96b8468a-3267-11e5-96c2-bb38c302d07e.png)

Kind regards,
Darlelet

**Comment by adamwtow** [comment] 2015-08-12 02:19
I am getting the same thing on my Ubuntu Desktop 14.04 LTS.

**Comment by Lnd-stoL** [comment] 2015-09-29 21:18
I think there is an issue opened for that already
https://github.com/snwh/paper-gtk-theme/issues/168

**Comment by snwh** [comment] 2016-03-17 00:26
duplicate of #168

**Closed by snwh** 2016-03-17 00:26 UTC
