### ISSUE TITLE
Text not visible in folder tabs

### ISSUE THREAD

**Issue by kartikarora** [snwh/paper-gtk-theme#154] opened 2015-04-29 05:08 UTC
After the update on 27th April, the folder tabs have a white background and white text, making it invisible. Same with the view switching buttons on the right hand side

I'm running Ubuntu 14.04 with Unity. I've installed the theme from your ppa.

![screenshot from 2015-04-27 15 01 58](https://cloud.githubusercontent.com/assets/6591617/7385054/faac6216-ee5b-11e4-8699-39a74befcdfc.png)
![screenshot from 2015-04-27 15 02 20](https://cloud.githubusercontent.com/assets/6591617/7385055/fabb2828-ee5b-11e4-8c68-585550231f48.png)

**Comment by Lowseling** [comment] 2015-05-15 17:18
Same problem here :\

**Comment by chipset95** [comment] 2015-05-17 06:04
@Lowseling Thanks, looks better now! :)

**Comment by snwh** [comment] 2016-03-16 23:50
Duplicate of #168

**Closed by snwh** 2016-03-16 23:50 UTC
