### ISSUE TITLE
Little white dots corner of the folders screen

### ISSUE THREAD

**Issue by ozberk** [snwh/paper-gtk-theme#363] opened 2016-06-03 00:54 UTC
- the GNOME/GTK version that is on your system: UNITY (Don't know exactly)
- which Linux distribution you are running: UBUNTU 16.04 LTS
- the version of Paper you are using: Just installed it :/ 

Greate theme and I really like the effort you did on this theme. Thank you. But you need to solve this little issue. There are two annoying dots the cornest of this screen. (Folders)

![ekran goruntusu - 2016-06-03 03-49-43](https://cloud.githubusercontent.com/assets/6108475/15765557/c26c897a-293e-11e6-97c1-f05b6ec8527a.png)
![ekran goruntusu - 2016-06-03 03-50-01](https://cloud.githubusercontent.com/assets/6108475/15765558/c270c83c-293e-11e6-939d-e012a6f391f4.png)

New update it doesn't affect just Folders also the software center here there is another screenshot. 
![ekran goruntusu - 2016-06-03 04-02-31](https://cloud.githubusercontent.com/assets/6108475/15765663/04d935e6-2940-11e6-8f99-07826d01ddb8.png)

**Comment by snwh** [comment] 2016-06-03 01:13
Duplicate of #300

**Closed** 2016-06-03 01:16 UTC
Labels: duplicate
