### ISSUE TITLE
Nemo trees don't show up correctly

### ISSUE THREAD

**Issue by alpapad** [snwh/paper-gtk-theme#304] opened 2016-04-17 17:34 UTC
Nemo trees don't show up correctly. This is fedora 23.

![image](https://cloud.githubusercontent.com/assets/1186525/14588817/ab8e948c-04db-11e6-8492-4df840b78c2f.png)

**Comment by ikelos** [comment] 2016-04-17 17:35
I think this is a duplicate of #302 (GtkTreeViews in general), I didn't spot that nemo does it too.

**Comment by alpapad** [comment] 2016-04-17 19:21
Yes, it seems like trees don't get rendered properly. In nemo the result is
unreadable, so it is a show-stopper.

**Closed** 2016-04-17 19:23 UTC
