### ISSUE TITLE
Window in window look

### ISSUE THREAD

**Issue by Kyle-Helmick** [snwh/paper-gtk-theme#345] opened 2016-05-07 04:08 UTC
- GTK 3.18.9
- Ubuntu 16.04
- Paper-gtk-theme 2.0+r266~daily~ubuntu14.04.1

As the title suggests
![gitupload](https://cloud.githubusercontent.com/assets/18430725/15090106/c1126e00-13d6-11e6-97fa-0d6dbccf42b3.png)

Notice right under the window options (close, minimize, maximize) there is a whitish triangle, and similarly one on the right side.

**Comment by snwh** [comment] 2016-05-07 21:59
Duplicate of #319

**Closed** 2016-05-07 22:00 UTC
Labels: duplicate
