### ISSUE TITLE
Increase the size of close, minimize and maximize buttons in gtk 3.20

### ISSUE THREAD

**Issue by WantedFish** [snwh/paper-gtk-theme#379] opened 2016-07-09 14:14 UTC
- GNOME/GTK version: 3.20
- Linux distribution: Ubuntu 16.04 
- the version of Paper you are using: Latest

Increase the size of close, minimize and maximize buttons in gtk 3.20

**Comment by ikelos** [comment] 2016-07-09 14:33
This is an enhancement request, and is also a duplicate of #315.

**Closed** 2016-07-10 14:57 UTC
